apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  labels:
    app: chat-app
spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
  - port: 8501        # Service port
    targetPort: 8501  # Container port
    nodePort: 30080   # External port (30000-32767 range)
    protocol: TCP
    name: http